name: Build and deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: Extract branch name
        run: echo ::set-env name=BRANCH_NAME::$(echo ${{ github.ref }} | sed 's/\//_/g' | sed 's/refs_heads_//g')
      - name: Branch name
        run: echo running on branch ${BRANCH_NAME}
      - name: Build the Docker image
        run: docker build . -t dataprata.azurecr.io/dataprata:${BRANCH_NAME}
      - name: Login to Registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin dataprata.azurecr.io
      - name: Publish to Registry
        run: docker push dataprata.azurecr.io/dataprata:${BRANCH_NAME}
