name: Docker Image CI

on:
  push:
    branches: 
      - master
      - develop

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ringmera:${{ github.ref }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ringmera.azurecr.io/ringmera
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: azurecr.io
        tags: "latest,${{ github.ref }}"
